common: &default_settings
  license_key: <%= ENV['studenthub_newrelic_key'] %>

  agent_enabled: auto

  app_name: Student Hub
  monitor_mode: true
  developer_mode: false

  log_level: info
  log_file_path: 'log'
  log_file_name: 'newrelic_agent.log'

  ssl: true

  browser_monitoring:
      auto_instrument: true

  audit_log:
    enabled: false

  capture_params: true


  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

# Application Environments
# ------------------------------------------

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true
  app_name: Student Hub (Production)

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: Student Hub (Staging)
