# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

development:
    secret_key_base: a293340f45d16c8e8f9002d8adabb13a47f9b97b9006f124f6c6f991728ad55006b39734494fdf9817a9b2ac2407681f9f7b0ba767a52f42b0ed81e591aca2f9

test:
    secret_key_base: 2abfbb961632879ee5e6a835936e9fdddce11f720882f6b2c2b09a39e006a40549499349f183e602966df111bb612001da75cde53309aa74e91315ad6127184d

production:
    secret_key_base: <%= ENV["studenthub_secret_key_base"] %>

staging:
    secret_key_base: <%= ENV["studenthub_secret_key_base"] %>

