location_tree = {
    "Cape Town" => {
        "City Bowl" => {
            "Bo-Kaap",
            "Devil's Peak",
            "De Waterkant",
            "Foreshore",
            "Gardens",
            "Higgovale",
            "Lower Vrede",
            "Oranjezicht",
            "Salt River",
            "Schotse Kloof",
            "Tamboerskloof",
            "University Estate",
            "Vredehoek",
            "Walmer Estate",
            "Woodstock",
            "Zonnebloem"
        },
        "Northern Suburbs" => {
            "Bellville",
            "Bothasig",
            "Brackenfell",
            "Brooklyn",
            "Durbanville",
            "Edgemead",
            "Elsie's River",
            "Goodwood",
            "Kensington",
            "Kraaifontein",
            "Kuils River",
            "Maitland",
            "Monte Vista",
            "Panorama",
            "Parow",
            "Thornton",
            "Table View"
        },
        "Atlantic Seaboard" => {
            "Bantry Bay",
            "Camps Bay",
            "Clifton",
            "Fresnaye",
            "Green Point",
            "Hout Bay",
            "Imizamo Yethu",
            "Llandudno",
            "Mouille Point",
            "Sea Point",
            "Three Anchor Bay"
        },
        "Southern Suburbs" => {
            "Bergvliet",
            "Bishopscourt",
            "Claremont",
            "Constantia",
            "Diep River",
            "Heathfield",
            "Kenilworth",
            "Kenwyn",
            "Kreupelbosch",
            "Meadowridge",
            "Mowbray",
            "Newlands",
            "Observatory",
            "Pinelands",
            "Plumstead",
            "Retreat",
            "Rondebosch",
            "Rondebosch East",
            "Rosebank",
            "Steenberg",
            "Tokai",
            "Wynberg"
        },
        "South Peninsula" => {
            "Capri Village",
            "Clovelly",
            "Fish Hoek",
            "Glencairn",
            "Kalk Bay",
            "Kommetjie",
            "Lakeside",
            "Marina da Gama",
            "Masiphumelele",
            "Muizenberg",
            "Noordhoek",
            "Ocean View",
            "Scarborough",
            "Simon's Town",
            "St James",
            "Sunnydale",
            "Sun Valley"
        },
        "Cape Flats" => {
            "Athlone",
            "Belhar",
            "Bishop Lavis",
            "Blue Downs",
            "Bonteheuwel",
            "Crawford",
            "Delft",
            "Electric City",
            "Elsie's River",
            "Epping",
            "Grassy Park",
            "Hanover Park",
            "Kalksteenfontein",
            "Khayelitsha",
            "Langa",
            "Lansdowne",
            "Lavender Hill",
            "Lotus River",
            "Macassar",
            "Manenberg",
            "Mitchell's Plain",
            "Nyanga",
            "Ottery",
            "Pellican Park",
            "Philippi",
            "Samora Micheal",
            "Strandfontein",
            "Wetton"
        },
        "Helderberg" => {
            "Gordon's Bay",
            "Somerset West",
            "Strand"
        },
        "West Coast" => [
            "Bloubergstrand",
            "Milnerton",
            "Tableview",
            "West Beach",
            "Parklands"
        ]
    }
}
